import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "敏迪医疗",
  description: "Generated by create next app",
};

import TopNav  from "@/ui/TopNav"
import Footer from "@/ui/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative`}
      >
          <div className=" h-12 bg-[#5ABFAB]">
            <div className="container h-full mx-auto bg-amber-200">
              ddd
            </div>
          </div>

          <div className="sticky top-0 left-0 right-0 z-20">
            <TopNav />
          </div>
          <div className="min-h-screen">
            {children}
          </div>

          <div>
            <Footer />
          </div>
      </body>
    </html>
  );
}
